include("sv_infodb.lua")
include("sv_job.lua")
include("sv_round.lua")
include("sv_corpse.lua")
include("sv_grab.lua")
include("sv_task.lua")
include("sv_char.lua")
include("sv_craft.lua")
include("sh_craft_list.lua")

AddCSLuaFile("sh_craft_list.lua")