Ply_Models = {
    ["male_01"] = {
        casual = {"models/player/casual/male_01.mdl"},
        science = {"models/player/Apsci_Male_01.mdl"},
        security = {"models/player/guard_pack/guard_01.mdl"},
        work = {"models/Humans/Group03/male_01.mdl"},
        engineer = {"models/player/engineer/engineer_van.mdl"},
        cook = {"models/player/Group01/male_01.mdl"},
    },
    ["male_02"] = {
        casual = {"models/player/casual/male_02.mdl"},
        science = {"models/player/Apsci_Male_02.mdl"},
        security = {"models/player/guard_pack/guard_02.mdl"},
        work = {"models/Humans/Group03/male_02.mdl"},
        engineer = {"models/player/engineer/engineer_ted.mdl"},
        cook = {"models/player/Group01/male_02.mdl", color = Color(255,255,255)},
    },
    ["male_03"] = {
        casual = {"models/player/casual/male_03.mdl"},
        science = {"models/player/Apsci_Male_03.mdl"},
        security = {"models/player/guard_pack/guard_03.mdl"},
        work = {"models/Humans/Group03/male_03.mdl"},
        engineer = {"models/player/engineer/engineer_joe.mdl"},
        cook = {"models/player/Group01/male_03.mdl", color = Color(255,255,255)},
    },
    ["male_04"] = {
        casual = {"models/player/casual/male_04.mdl"},
        science = {"models/player/Apsci_Male_04.mdl"},
        security = {"models/player/guard_pack/guard_04.mdl"},
        work = {"models/player/Group03/male_04.mdl"},
        engineer = {"models/player/engineer/engineer_eric.mdl"},
        cook = {"models/player/Group01/male_04.mdl", color = Color(255,255,255)},
    },
    ["male_05"] = {
        casual = {"models/player/casual/male_05.mdl"},
        science = {"models/player/Apsci_Male_05.mdl"},
        security = {"models/player/guard_pack/guard_05.mdl"},
        work = {"models/Humans/Group03/male_05.mdl"},
        engineer = {"models/player/engineer/engineer_art.mdl"},
        cook = {"models/player/Group01/male_05.mdl", color = Color(255,255,255)},
    },
    ["male_06"] = {
        casual = {"models/player/casual/male_06.mdl"},
        science = {"models/player/Apsci_Male_06.mdl"},
        security = {"models/player/guard_pack/guard_06.mdl"},
        work = {"models/Humans/Group03/male_06.mdl"},
        engineer = {"models/player/engineer/engineer_art.mdl"},
        cook = {"models/player/Group01/male_06.mdl", color = Color(255,255,255)},
    },
    ["male_07"] = {
        casual = {"models/player/casual/male_07.mdl"},
        science = {"models/player/Apsci_Male_07.mdl"},
        security = {"models/player/guard_pack/guard_07.mdl"},
        work = {"models/Humans/Group03/male_07.mdl"},
        engineer = {"models/player/engineer/engineer_mike.mdl"},
        cook = {"models/player/Group01/male_07.mdl", color = Color(255,255,255)},
    },
    ["male_08"] = {
        casual = {"models/player/casual/male_08.mdl"},
        science = {"models/player/Apsci_Male_08.mdl"},
        security = {"models/player/guard_pack/guard_08.mdl"},
        work = {"models/Humans/Group03/male_08.mdl"},
        engineer = {"models/player/engineer/engineer_balaclava.mdl"},
        cook = {"models/player/Group01/male_08.mdl", color = Color(255,255,255)},
    },
    ["male_09"] = {
        casual = {"models/player/casual/male_09.mdl"},
        science = {"models/player/Apsci_Male_09.mdl"},
        security = {"models/player/guard_pack/guard_09.mdl"},
        work = {"models/Humans/Group03/male_09.mdl"},
        engineer = {"models/player/engineer/engineer_balaclava.mdl"},
        cook = {"models/player/Group01/male_09.mdl", color = Color(255,255,255)},
    },
}
--[[
FaceIndex = {
    "male_01",
    "male_02",
    "male_03",
    "male_04",
    "male_05",
    "male_06",
    "male_07",
    "male_08",
    "male_09",
}
--]]